@file:Suppress("unused")

package ms.mattschlenkrich.billsprojectionv2.common

const val DB_NAME = "bills2.db"
const val DB_VERSION = 2
const val BILLS_DATABASE = "BillsDatabase"

const val SQLITE_DATE = "yyyy-LL-dd"
const val SQLITE_TIME = "yyyy-LL-dd HH:mm:ss"
const val DATE_CHECK = "yyyy-MM-dd"
const val DATE_CHECK_WITH_YEAR = "?"
const val DISPLAY_DATE = "EEE dd LLL"
const val DISPLAY_DATE_WITH_YEAR = "EEE dd LLL /yy"

const val FRAG_ACCOUNT_ADD = "AccountAdd"
const val FRAG_ACCOUNTS = "Accounts"
const val FRAG_ACCOUNT_TYPE_ADD = "AccountTypeAdd"
const val FRAG_ACCOUNT_TYPES = "AccountTypes"
const val FRAG_ACCOUNT_TYPE_UPDATE = "AccountTypeUpdate"
const val FRAG_ACCOUNT_UPDATE = "AccountUpdate"
const val FRAG_BUDGET_RULES = "BudgetRules"
const val FRAG_DAYS_OF_WEEK = "DaysOfWeek"
const val FRAG_BUDGET_RULE_ADD = "BudgetRuleAdd"
const val FRAG_BUDGET_RULE_UPDATE = "BudgetRuleUpdate"
const val FRAG_TRANSACTIONS = "Transactions"
const val FRAG_TRANS_ADD = "TransactionAdd"
const val FRAG_TRANS_UPDATE = "TransactionUpdate"
const val FRAG_BUDGET_VIEW = "BudgetView"
const val FRAG_BUDGET_ITEM_ADD = "BudgetItemAdd"
const val FRAG_BUDGET_ITEM_UPDATE = "BudgetItemUpdate"

const val ADAPTER_BUDGET_RULE = "BudgetRuleAdapter"
const val ADAPTER_ACCOUNT = "AccountAdapter"
const val ADAPTER_ACCOUNT_TYPE = "AccountTypeAdapter"
const val ADAPTER_TRANSACTION = "TransactionAdapter"

const val TABLE_ACCOUNT_TYPES = "accountTypes"
const val TYPE_ID = "typeId"
const val ACCOUNT_TYPE = "accountType"
const val KEEP_BALANCE = "keepTotals"
const val IS_ASSET = "isAsset"
const val TALLY_OWING = "tallyOwing"
const val KEEP_MILEAGE = "keepMileage"
const val ALLOW_PENDING = "allowPending"
const val ACCT_DISPLAY_AS_ASSET = "displayAsAsset"
const val ACCT_IS_DELETED = "acctIsDeleted"
const val ACCT_UPDATE_TIME = "acctUpdateTime"

const val TABLE_ACCOUNTS = "accounts"
const val ACCOUNT_ID = "accountId"
const val ACCOUNT_NAME = "accountName"
const val ACCOUNT_NUMBER = "accountNumber"
const val ACCOUNT_TYPE_ID = "accountTypeId"
const val ACCOUNT_BUDGETED_AMOUNT = "accBudgetedAmount"
const val ACCOUNT_BALANCE = "accountBalance"
const val ACCOUNT_OWING = "accountOwing"
const val ACCOUNT_CREDIT_LIMIT = "accountCreditLimit"
const val ACCOUNT_IS_DELETED = "accIsDeleted"
const val ACCOUNT_UPDATE_TIME = "accUpdateTime"
const val VIEW_ACCOUNT_WITH_TYPE = "accountWithType"

const val TABLE_BUDGET_RULES = "budgetRules"
const val RULE_ID = "ruleId"
const val BUDGET_RULE_NAME = "budgetRuleName"
const val BUD_TO_ACCOUNT_ID = "budToAccountId"
const val BUD_FROM_ACCOUNT_ID = "budFromAccountId"
const val BUDGET_AMOUNT = "budgetAmount"
const val BUD_FIXED_AMOUNT = "budFixedAmount"
const val BUD_IS_PAY_DAY = "budIsPayDay"
const val BUD_IS_AUTO_PAY = "budIsAutoPay"
const val BUD_START_DATE = "budStartDate"
const val BUD_END_DATE = "budEndDate"
const val BUD_DAY_OF_WEEK_ID = "budDayOfWeekId"
const val BUD_FREQUENCY_TYPE_ID = "budFrequencyTypeId"
const val BUD_FREQUENCY_COUNT = "budFrequencyCount"
const val BUD_LEAD_DAYS = "budLeadDays"
const val BUD_IS_DELETED = "budIsDeleted"
const val BUD_UPDATE_TIME = "budUpdateTime"

const val TABLE_BUDGET_ITEMS = "budgetItems"
const val BI_BUDGET_RULE_ID = "biRuleId"
const val BI_PROJECTED_DATE = "biProjectedDate"
const val BI_TO_ACCOUNT_ID = "biToAccountId"
const val BI_FROM_ACCOUNT_ID = "biFromAccountId"
const val BI_ACTUAL_DATE = "biActualDate"
const val BI_PAY_DAY = "biPayDay"
const val BI_BUDGET_NAME = "biBudgetName"
const val BI_IS_PAY_DAY_ITEM = "biIsPayDayItem"
const val BI_PROJECTED_AMOUNT = "biProjectedAmount"
const val BI_IS_AUTOMATIC = "biIsAutomatic"
const val BI_IS_FIXED = "bIsFixed"
const val BI_IS_MANUALLY_ENTERED = "biManuallyEntered"
const val BI_LOCKED = "biLocked"
const val BI_IS_COMPLETED = "biIsCompleted"
const val BI_IS_CANCELLED = "biIsCancelled"
const val BI_IS_DELETED = "biIsDeleted"
const val BI_UPDATE_TIME = "biUpdateTime"

const val TABLE_TRANSACTION = "transactions"
const val TRANSACTION_ID = "transId"
const val TRANSACTION_DATE = "transDate"
const val TRANS_BUDGET_RULE_ID = "transRuleId"
const val TRANSACTION_TO_ACCOUNT_ID = "transToAccountId"
const val TRANSACTION_TO_ACCOUNT_PENDING = "transToAccountPending"
const val TRANSACTION_FROM_ACCOUNT_ID = "transFromAccountId"
const val TRANSACTION_FROM_ACCOUNT_PENDING = "transFromAccountPending"
const val TRANSACTION_NAME = "transName"
const val TRANSACTION_NOTE = "transNote"
const val TRANSACTION_AMOUNT = "transAmount"
const val TRANS_IS_PENDING = "transIsPending"
const val TRANS_IS_DELETED = "transIsDeleted"
const val TRANS_UPDATE_TIME = "transUpdateTime"

const val REQUEST_TO_ACCOUNT = "toAccount"
const val REQUEST_FROM_ACCOUNT = "fromAccount"

const val DAY_MONDAY = "Monday"
const val DAY_TUESDAY = "Tuesday"
const val DAY_WEDNESDAY = "Wednesday"
const val DAY_THURSDAY = "Thursday"
const val DAY_FRIDAY = "Friday"
const val DAY_SATURDAY = "Saturday"
const val DAY_SUNDAY = "Sunday"
const val DAY_WEEK_DAY = "Week Day"
const val DAY_ANY_DAY = "Any Day"
const val DAY_PAY_DAY = "Pay Day"

const val INTERVAL_WEEKLY = "Weekly"
const val INTERVAL_MONTHLY = "Monthly"
const val INTERVAL_YEARLY = "Yearly"
const val INTERVAL_ON_PAY_DAY = "On Payday"
const val INTERVAL_SPECIAL = "Special"
const val INTERVAL_ONE_TIME = "One Time"

