@file:Suppress("unused")

package ms.mattschlenkrich.billsprojectionv2

const val SQLITE_DATE = "yyyy-LL-dd"
const val SQLITE_TIME = "yyyy-LL-dd HH:mm:ss"
const val DATE_CHECK = "yyyy-MM-dd"
const val DATE_CHECK_WITH_YEAR = "?"
const val DISPLAY_DATE = "EEE dd LLL"
const val DISPLAY_DATE_WITH_YEAR = "EEE dd LLL /yy"

const val FRAG_ACCOUNT_ADD = "AccountAdd"
const val FRAG_ACCOUNTS = "accounts"
const val FRAG_ACCOUNT_TYPE_ADD = "AccountTypeAdd"
const val FRAG_ACCOUNT_TYPES = "AccountTypes"
const val FRAG_ACCOUNT_TYPE_UPDATE = "AccountTypeUpdate"
const val FRAG_ACCOUNT_UPDATE = "AccountUpdate"
const val FRAG_BUDGET_RULES = "BudgetRules"
const val FRAG_DAYS_OF_WEEK = "DaysOfWeek"
const val FRAG_BUDGET_RULE_ADD = "BudgetRuleAdd"
const val FRAG_BUDGET_RULE_UPDATE = "BudgetRuleUpdate"
const val FRAG_TRANSACTIONS = "Transactions"
const val FRAG_BUDGET_VIEW = "BudgetView"

const val ADAPTER_BUDGET_RULE = "BudgetRuleAdapter"
const val ADAPTER_ACCOUNT = "AccountAdapter"
const val ADAPTER_ACCOUNT_TYPE = "AccountTypeAdapter"

const val TABLE_ACCOUNT_TYPES = "accountTypes"
const val TYPE_ID = "typeId"
const val ACCOUNT_TYPE = "accountType"
const val KEEP_TOTALS = "keepTotals"
const val IS_ASSET = "isAsset"
const val TALLY_OWING = "tallyOwing"
const val KEEP_MILEAGE = "keepMileage"
const val IS_DELETED = "isDeleted"
const val UPDATE_TIME = "updateTime"

const val TABLE_ACCOUNTS = "accounts"
const val ACCOUNT_ID = "accountId"
const val ACCOUNT_NAME = "accountName"
const val ACCOUNT_TYPE_ID = "accountTypeId"
const val ACCOUNT_BALANCE = "accountBalance"
const val ACCOUNT_OWING = "accountOwing"

const val TABLE_DAYS_OF_WEEK = "daysOfWeek"
const val DAY_ID = "dayId"
const val DAY_OF_WEEK = "dayOfWeek"

const val TABLE_FREQUENCY_TYPES = "frequencyTypes"
const val FREQUENCY_ID = "frequencyId"
const val FREQUENCY_TYPE = "frequencyType"

const val TABLE_BUDGET_RULES = "budgetRules"
const val RULE_ID = "RuleID"
const val BUDGET_RULE_NAME = "budgetRuleName"
const val TO_ACCOUNT_ID = "toAccountId"
const val FROM_ACCOUNT_ID = "fromAccountId"
const val AMOUNT = "amount"
const val FIXED_AMOUNT = "fixedAmount"
const val IS_PAY_DAY = "isPayDay"
const val IS_AUTO_PAY = "isAutoPay"
const val START_DATE = "startDate"
const val END_DATE = "endDate"
const val DAY_OF_WEEK_ID = "dayOfWeekId"
const val FREQUENCY_TYPE_ID = "frequencyTypeId"
const val FREQUENCY_COUNT = "frequencyCount"
const val LEAD_DAYS = "leadDays"

const val TABLE_TRANSACTIONS = "transactions"
const val TRANSACTION_ID = "transId"
const val TRANSACTION_DATE = "transDate"
const val BUDGET_RULE_ID = "bRuleId"
const val TRANSACTION_NAME = "transName"
const val TRANSACTION_NOTE = "transNote"

const val REQUEST_TO_ACCOUNT = "toAccount"
const val REQUEST_FROM_ACCOUNT = "fromRequest"

