package ms.mattschlenkrich.billsprojectionv2

const val DB_NAME = "bills2.db"
const val DB_VERSION = 2
const val BILLS_DATABASE = "BillsDatabase"

const val SQLITE_DATE = "yyyy-LL-dd"
const val SQLITE_TIME = "yyyy-LL-dd HH:mm:ss"
const val DATE_CHECK = "yyyy-MM-dd"
const val DATE_CHECK_WITH_YEAR = "?"
const val DISPLAY_DATE = "EEE dd LLL"
const val DISPLAY_DATE_WITH_YEAR = "EEE dd LLL /yy"

const val FRAG_ACCOUNT_ADD = "AccountAdd"
const val FRAG_ACCOUNTS = "Accounts"
const val FRAG_ACCOUNT_TYPE_ADD = "AccountTypeAdd"
const val FRAG_ACCOUNT_TYPES = "AccountTypes"
const val FRAG_ACCOUNT_TYPE_UPDATE = "AccountTypeUpdate"
const val FRAG_ACCOUNT_UPDATE = "AccountUpdate"
const val FRAG_BUDGET_RULES = "BudgetRules"
const val FRAG_DAYS_OF_WEEK = "DaysOfWeek"
const val FRAG_BUDGET_RULE_ADD = "BudgetRuleAdd"
const val FRAG_BUDGET_RULE_UPDATE = "BudgetRuleUpdate"
const val FRAG_TRANSACTIONS = "Transactions"
const val FRAG_TRANS_ADD = "TransactionAdd"
const val FRAG_TRANS_UPDATE = "TransactionUpdate"
const val FRAG_BUDGET_VIEW = "BudgetView"
const val FRAG_BUDGET_VIEW_ADD = "BudgetViewAdd"
const val FRAG_BUDGET_VIEW_UPDATE = "BudgetViewUpdate"

const val ADAPTER_BUDGET_RULE = "BudgetRuleAdapter"
const val ADAPTER_ACCOUNT = "AccountAdapter"
const val ADAPTER_ACCOUNT_TYPE = "AccountTypeAdapter"
const val ADAPTER_TRANSACTION = "TransactionAdapter"

const val TABLE_ACCOUNT_TYPES = "accountTypes"
const val TYPE_ID = "typeId"
const val ACCOUNT_TYPE = "accountType"
const val KEEP_TOTALS = "keepTotals"
const val IS_ASSET = "isAsset"
const val TALLY_OWING = "tallyOwing"
const val KEEP_MILEAGE = "keepMileage"
const val ACCT_IS_DELETED = "acctIsDeleted"
const val ACCT_UPDATE_TIME = "acctUpdateTime"
const val ACCT_DISPLAY_AS_ASSET = "displayAsAsset"

const val TABLE_ACCOUNTS = "accounts"
const val ACCOUNT_ID = "accountId"
const val ACCOUNT_NAME = "accountName"
const val ACCOUNT_TYPE_ID = "accountTypeId"
const val ACCOUNT_BUDGETED_AMOUNT = "accBudgetedAmount"
const val ACCOUNT_BALANCE = "accountBalance"
const val ACCOUNT_OWING = "accountOwing"
const val ACCOUNT_IS_DELETED = "accIsDeleted"
const val ACCOUNT_UPDATE_TIME = "accUpdateTime"

const val TABLE_BUDGET_RULES = "budgetRules"
const val RULE_ID = "ruleId"
const val BUDGET_RULE_NAME = "budgetRuleName"
const val BUD_TO_ACCOUNT_ID = "budToAccountId"
const val BUD_FROM_ACCOUNT_ID = "budFromAccountId"
const val BUDGET_AMOUNT = "budgetAmount"
const val BUD_FIXED_AMOUNT = "budFixedAmount"
const val BUD_IS_PAY_DAY = "budIsPayDay"
const val BUD_IS_AUTO_PAY = "budIsAutoPay"
const val BUD_START_DATE = "budStartDate"
const val BUD_END_DATE = "budEndDate"
const val BUD_DAY_OF_WEEK_ID = "budDayOfWeekId"
const val BUD_FREQUENCY_TYPE_ID = "budFrequencyTypeId"
const val BUD_FREQUENCY_COUNT = "budFrequencyCount"
const val BUD_LEAD_DAYS = "budLeadDays"
const val BUD_IS_DELETED = "budIsDeleted"
const val BUD_UPDATE_TIME = "budUpdateTime"

const val TABLE_BUDGET_VIEW = "budgetView"
const val BV_BUDGET_RULE_ID = "bvRuleId"
const val BV_PROJECTED_DATE = "bvProjectedDate"
const val BV_TO_ACCOUNT_ID = "bvToAccountId"
const val BV_FROM_ACCOUNT_ID = "bvFromAccountId"
const val BV_ACTUAL_DATE = "bvActualDate"
const val BV_PAY_DAY = "bvPayDay"
const val BV_BUDGET_NAME = "bvBudgetName"
const val BV_IS_PAY_DAY_ITEM = "bvIsPayDayItem"
const val BV_PROJECTED_AMOUNT = "bvProjectedAmount"
const val BV_IS_AUTOMATIC = "bvIsAutomatic"
const val BV_IS_FIXED = "bvIsFixed"
const val BV_IS_MANUALLY_ENTERED = "bvManuallyEntered"
const val BV_IS_COMPLETED = "bvIsCompleted"
const val BV_IS_CANCELLED = "bvIsCancelled"
const val BV_IS_DELETED = "bvIsDeleted"
const val BV_UPDATE_TIME = "bvUpdateTime"

const val TABLE_TRANSACTION = "transactions"
const val TRANSACTION_ID = "transId"
const val TRANSACTION_DATE = "transDate"
const val TRANS_BUDGET_RULE_ID = "transRuleId"
const val TRANSACTION_TO_ACCOUNT_ID = "transToAccountId"
const val TRANSACTION_FROM_ACCOUNT_ID = "transFromAccountId"
const val TRANSACTION_NAME = "transName"
const val TRANSACTION_NOTE = "transNote"
const val TRANSACTION_AMOUNT = "transAmount"
const val TRANS_IS_PENDING = "transIsPending"
const val TRANS_IS_DELETED = "transIsDeleted"
const val TRANS_UPDATE_TIME = "transUpdateTime"

const val REQUEST_TO_ACCOUNT = "toAccount"
const val REQUEST_FROM_ACCOUNT = "fromAccount"

