package ms.mattschlenkrich.billsprojectionv2.ui.theme

import androidx.compose.ui.graphics.Color

// Light Colors
val LightPrimary = Color(0xFF073763)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFD3E4FF)
val LightOnPrimaryContainer = Color(0xFF001C38)
val LightSecondary = Color(0xFF00A86B)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFA9F7BB)
val LightOnSecondaryContainer = Color(0xFF00210E)
val LightTertiary = Color(0xFFBC131F)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFFFDAD6)
val LightOnTertiaryContainer = Color(0xFF410002)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFFFFBFE)
val LightOnBackground = Color(0xFF1A1C1E)
val LightSurface = Color(0xFFFFFBFE)
val LightOnSurface = Color(0xFF1A1C1E)
val LightSurfaceVariant = Color(0xFFE1E2EC)
val LightOnSurfaceVariant = Color(0xFF44474E)
val LightOutline = Color(0xFF74777F)

// Dark Colors
val DarkPrimary = Color(0xFFD0E4FF)
val DarkOnPrimary = Color(0xFF00315C)
val DarkPrimaryContainer = Color(0xFF004787)
val DarkOnPrimaryContainer = Color(0xFFD3E4FF)
val DarkSecondary = Color(0xFFA9F7BB)
val DarkOnSecondary = Color(0xFF00391D)
val DarkSecondaryContainer = Color(0xFF00522C)
val DarkOnSecondaryContainer = Color(0xFFA9F7BB)
val DarkTertiary = Color(0xFFFFB4AB)
val DarkOnTertiary = Color(0xFF690005)
val DarkTertiaryContainer = Color(0xFF93000A)
val DarkOnTertiaryContainer = Color(0xFFFFDAD6)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF1A1C1E)
val DarkOnBackground = Color(0xFFE2E2E6)
val DarkSurface = Color(0xFF1A1C1E)
val DarkOnSurface = Color(0xFFE2E2E6)
val DarkSurfaceVariant = Color(0xFF3F474D)
val DarkOnSurfaceVariant = Color(0xFFD1E4FF)
val DarkOutline = Color(0xFF8D9199)

// Branded Green
val AppIconGreen = Color(0xFF9CED79)
val AppIconGreenDark = Color(0xFF29A860)